### ISSUE TITLE
Functions Framework does not work with the Pub/Sub emulator

### ISSUE THREAD

**Issue by RomikimoR** [GoogleCloudPlatform/functions-framework-python#23]
Hello,

I am trying to emulate the behavior of my application.  
To do so I use the Pub/Sub Emulator and the Google cloud function emulator.
The cloud function I created looks like the image following and is supposed to be triggered by an event :
![image](https://user-images.githubusercontent.com/27961680/75333359-500b4800-5886-11ea-937b-2ab4150260c3.png)

Both emulators are communicating without issue.
I  followed the example of this repository: https://github.com/GoogleCloudPlatform/functions-framework-nodejs to link them.

When, following the example, I use this command line: 

> curl -d "@mockPubsub.json" -X POST \
>   -H "Ce-Type: true" \
>   -H "Ce-Specversion: true" \
>   -H "Ce-Source: true" \
>   -H "Ce-Id: true" \
>   -H "Content-Type: application/json" \
>   http://localhost:8080

 On my Cloud function emulator I do receive this : 
![image](https://user-images.githubusercontent.com/27961680/75333302-2baf6b80-5886-11ea-9486-1296eca89956.png)

So this is exactly what I want. 
Yet, I do not want to use the command line to send messages but I want the cloud function to be triggered by a Pub/Sub event.

Here you can see the methods creating: 
I. a pull subscription
II. a push subsciption
III. publishing messages

![image](https://user-images.githubusercontent.com/27961680/75333933-49310500-5887-11ea-8aee-cf44907d04ed.png)

However When I want to publish messages, the Pub/Sub emulator detect the connection:

> [pubsub] INFO: Detected HTTP/2 connection.

But then the Cloud Function emulator does not receive the data, although it detects an event occurred: 
![image](https://user-images.githubusercontent.com/27961680/75334012-6a91f100-5887-11ea-8f8f-db677311144a.png)

I think it is probably because POSTING to a Gcloud Function needs some headers with the 'Ce-' prefix.
But searching a bit on how to add headers to my push subscriber I found out this wasn't possible.
It's possible I totally missed something...

I hope this is understandable.
Thank you

**Comment by di** [comment]
Thanks for the report, I'll take a look at this and see what's going on.

**Comment by wojtek-viirtue** [comment]
+1 on this.  I can confirm I'm seeing the same exact result for the same exact use case.

**Comment by isaldana** [comment]
It looks like when setting `Ce-Type`, `Ce-Specversion`, `Ce-Source`, and `Ce-Id` the request body is not `JSON` parsed. Unfortunately, when they are not set, only the `data` portion of the request are passed on the first parameter to the function. According to the samples for [Pub/Sub-triggered functions](https://cloud.google.com/functions/docs/testing/test-background), the first parameter should be a hash with the `data` and `attributes` fields. As is, it looks like `attributes` could not be accessed. I used the following command to test:

```curl --header "Content-Type: application/json" --request POST --data '{"data":"This is a message", "attributes":{"k1":"v1"}}' http://0.0.0.0:8091/```

on the following function

```python
def main(event, context):
    print(event, context)
```

with the following output

```
127.0.0.1 - - [01/Mar/2020 01:40:42] "POST / HTTP/1.1" 200 -
This is a message {event_id: , timestamp: , event_type: , resource: }
```

**Comment by uraniun** [comment]
I've made fork of this repo, that supports events from Pub/Sub. Not the cleanest/best solution, but it works for my needs. Hope this may help
https://github.com/uraniun/functions-framework-python

**Comment by RomikimoR** [comment]
I will try the fork!! Thank you a lot I really needed a patch even not the cleanest for this !

**Comment by grant** [comment]
Thanks for the report and workaround. As Dustin stated, we'll look into this (it may be similar with other frameworks).

**Comment by di** [comment]
Just a quick update here: we've decided to add support for these legacy-style Pub/Sub events. Hang tight while we roll this out, and thanks for your patience.

**Comment by dror-g** [comment]
Hi, not sure but I think it's related: 
When using the Python function code example from [Pub/Sub Tutorial](https://cloud.google.com/functions/docs/tutorials/pubsub#preparing_the_application)  
I get an error when using curl  to emulate an event (from nodejs framework, same as OP).
`main.py", line 17, in hello
    if 'data' in event:
TypeError: a bytes-like object is required, not 'str'
`
cheers

**Comment by di** [comment]
@dror-g It looks like your function expects a Pub/Sub message but you're calling it with headers that indicate that it's a binary CloudEvent instead.

Try calling it like so:

```
$ curl -d '{"data": {"hi": "there"}}' -X POST -H "Content-Type: application/json" http://localhost:8080
```

Where the value of `data` is what eventually becomes the `event` object in your function.

**Comment by dror-g** [comment]
Hi @di , yes, like OP I am trying to emulate Pub/Sub triggered function, and we both tried to post a mock.json file.  
functions-framework seems to be working as long as you BASE64 encode the body (as it is in the cloud) and enclose it in `{"data": {"data": "$B64_string"} }`.

Tried this function:
```
from json import loads
from base64 import b64decode


def wak(event, context):
    print("EVENT", event)
    if 'data' in event:
        data = loads(b64decode(event['data']).decode('utf-8'))
        print('data: ', data)
    else:
        raise RuntimeError('no data in event')
    return
```
  
What works:  
     
- started with `functions-framework --target wak --signature-type event`  
calling with:  `DATA=$(printf '{"some": "thing"}'|base64 -w 0) && curl -d '{"data": {"data": "'$DATA'"}}' -X POST -H "Content-Type: application/json" http://localhost:8080`  
  
- Deploying to the cloud and sending a message from Pub/Sub web UI (message body: {"some": "thing"}   ).  
  
- calling from gcloud cli with following command:  
` DATA=$(printf '{"some": "thing"}'|base64 -w 0) && gcloud functions call testFunc --region europe-west2 --data '{"data": "'$DATA'"}'  
- created notification on a bucket, uploaded file to bucket (`gsutil notification create -t test-topic -f json gs://test-func-bucket2`).  
  

What doesn't:  
started with `functions-framework --target wak --signature-type event`

mock.json:  
```
{
  "message": {
    "attributes": {
      "key": "value"
    },
    "data": "SGVsbG8gQ2xvdWQgUHViL1N1YiEgSGVyZSBpcyBteSBtZXNzYWdlIQ==",
    "messageId": "136969346945"
  },
  "subscription": "projects/myproject/subscriptions/mysubscription"
} 
```
  
- `curl -d "@mock.json" -X POST -H "Content-Type: application/json" http://localhost:8080`  -  
EVENT is null, getting:
```
RuntimeError: no data in event
127.0.0.1 - - [21/Apr/2020 20:36:30] "POST / HTTP/1.1" 500 -
```
  
- `curl -d '{"hi": "there"}' -X POST -H "Content-Type: application/json" http://localhost:8080` - 
EVENT is null, getting:
```
RuntimeError: no data in event
127.0.0.1 - - [21/Apr/2020 20:36:30] "POST / HTTP/1.1" 500 -
```
  
- `curl --data '{"data": {"hi": "there"}}' -X POST -H "Content-Type: application/json" http://localhost:8080`  
Returns:
```
EVENT {'hi': 'there'}
RuntimeError: no data in event
127.0.0.1 - - [21/Apr/2020 20:50:45] "POST / HTTP/1.1" 500 -
```

**Comment by 27Bslash6** [comment]
> Thanks for the report and workaround. As Dustin stated, we'll look into this (it may be a similar issue with other frameworks).

I had this same issue working with the nodejs pubsub client for cloud functions

**Comment by mikebridge** [comment]
Just so I'm clear, is this an issue with the functions framework, the pubsub emulator, someone's understanding of the correct payload format, or the (adapted) [documentation around the technique for connecting the emulator to the functions framework](https://github.com/GoogleCloudPlatform/functions-framework-nodejs)?   I'd like to try using the functions framework as part of an end-to-end test with the pubsub emulator but I'm not clear whether this would be a blocking issue.

**Comment by mikebridge** [comment]
Google's ["getting started" documentation](https://cloud.google.com/functions/docs/testing/test-background#pubsub-triggered_functions) describes the `event` as a python dict, but I can see that when posting via curl with the OP's test script will pass the event as a `str`.  So is the bug then with the http testing endpoint?  

Maybe the easiest workaround is to write a wrapper function just for testing that `json.loads` the event and passes it to the function?

**Comment by mikebridge** [comment]
While I'm at it, I see no reason why the example base64-encodes/decodes the text string _within the json payload_.  This just makes the Google documentation even more confusing than it already is.

**Comment by mikebridge** [comment]
The more I read the [google documentation](https://cloud.google.com/pubsub/docs/publisher), the more frustrated and confused I get.  Am I mistaken or is it *full* of errors?  As far as I can *tell* from running the example I just posted, the data payload is just a plain old `string`, and it's delivered in a Python `dict`.

But [here](https://cloud.google.com/pubsub/docs/publisher#publish) it says "When using JSON over REST, message data must be base64-encoded. ", but then nowhere in the examples does it do anything with base64 encoding.  And when using the `functions-framework`, I actually see no reason to base64-encode the _key_---it just gets passed through as a string.  Similarly, when I publish the function above, it's just a string.  It gets worse---the example encodes the data as a `byte-string`:

```python
future = publisher.publish(
        topic_path, data=data.encode("utf-8")  # data must be a bytestring.
    )
```

Soooo...  this example uses is a sequence of _bytes_, not a base64-encoded string.  Is there something that's base64-encoding them behind the scenes?  I have no idea.

**Comment by jacobg** [comment]
I'm also having an issue connecting the emulator to functions-framework. I'm publish a message with data={"foo": "bar"}, and the functions-framework shows the request comes in with the header `Content-Type: application/json` and body of:
```
{"subscription":"projects\\/myproject\\/subscriptions\\/mysubscription","message":{"data":"eyJmb28iOiAiYmFyIn0=","messageId":"52","attributes":{}}}
```

And yet when my function is called:
```python
def receive_event(event, context=None):
    print('receive_event(event={}, context={}'.format(event, context))
    print('receive_event event type {}'.format(type(event)))
```
It prints:
```
receive_event(event=, context={event_id: , timestamp: , event_type: , resource: }
receive_event event type <class 'str'>
```

Is the posted json above using this legacy format you're referring to? From the snippets pasted in earlier comments on this issue thread, it seems that perhaps `data` and `attributes` are no longer embedded in a `message` attribute? Still, there is no `attributes` key referenced in the functions framework.

I am publishing using an old version of `google-cloud-pubsub` version `0.27.0`, because I'm publishing from a Python 2 GAE app in local development. It's the last version that supports that environment, since the subsequent version uses grpc. See this issue:
https://github.com/googleapis/google-cloud-python/issues/5670#issuecomment-407225773

I'm probably going to just fork the functions-framework to make it work in this environment.

**Comment by jacobg** [comment]
Editing the `_run_legacy_event` function as follows seems to fix the issue:

```python
def _run_legacy_event(function, request):
    event_data = request.get_json()
    if not event_data:
        flask.abort(400)

    ###############
    # Need to add this code to make pubsub events work.
    if 'message' in event_data:
        if 'data' not in event_data:
            message = event_data['message']
            event_data['data'] = {
                'data': message.get('data'),
                'attributes': message.get('attributes')
            }
    ###############

    event_object = _Event(**event_data)
    data = event_object.data
    context = Context(**event_object.context)
    function(data, context)
```

**Comment by gabriel-young** [comment]
@di, any update on this? Looks like @jacobg's comment may be the solution for this bug?

**Comment by lrodorigo** [comment]
I can confirm that the bug is still there.
Trying to use functions-framork to emulate PubSub events coming from Google IoT Core.
The content of the `event` parameter is COMPLETELY DIFFERENT between the functions framework and the runtime.
While using the functions-framework only the content of the event parameter is only the value of the `data` key set in the request (base64-encoded string), while in the actual 'true' runtime the `data` is a *dict* containing the device `attributes` dict AND the `data` key.

If I try to put the following headers on the functions-framework request:
```
Ce-Type: false
Ce-Specversion: true
Ce-Source: true
Ce-Id: true
```
then, I get also the attribute, but it is not a dict (like in the true environment) but it is a serialized-json instead... so without modifying the function framework sources, the only workaround I found is to add the following, and send the curl request with the previous headers:
```
    if not isinstance(event,dict):
        event = json.loads(event)
```

Totally unusable. I expected better, really better from Google.

**Comment by anguillanneuf** [comment]
Thanks all @RomikimoR @wojtek-viirtue @isaldana @uraniun @dror-g @27Bslash6 @mikebridge @jacobg @gabriel-young @lrodorigo for your patience!

Functions Frameworks is now working with Pub/Sub Emulator! 🎉

![ff-emulator](https://user-images.githubusercontent.com/9518298/117225596-8a943d00-adc7-11eb-9752-c69a50a6d71e.jpg)

**Comment by frankie567** [comment]
Thanks @anguillanneuf for the added documentation about this.

However, I'm a bit confused here. The examples you show suppose the Cloud Function expects a `request` argument, which sounds to be a Flask `Request`:

```py
def hello(request):
    return "Hello world!"
```

However, unless there is something I miss here, the [official way of implementing a Pub/Sub Cloud Function](https://cloud.google.com/functions/docs/tutorials/pubsub) tells us to define function with two arguments: `event_data`, a dictionary containing Base64-encoded data, and `context`, a `google.cloud.functions.Context` object:

```py
def hello_pubsub(event, context):
    import base64

    print("""This Function was triggered by messageId {} published at {} to {}
    """.format(context.event_id, context.timestamp, context.resource["name"]))

    if 'data' in event:
        name = base64.b64decode(event['data']).decode('utf-8')
    else:
        name = 'World'
    print('Hello {}!'.format(name)))
```

If I try to debug those kind of functions using with the framework and the Pub/Sub emulator, I get this kind of error:

```
TypeError: argument of type 'Request' is not iterable
```

Obviously because we get a `Request` object instead of a dictionary.

So, what is the right way to debug a Pub/Sub Cloud Function?

**Comment by anguillanneuf** [comment]
@frankie567 Oh no, this issue was closed and I did not see your comment until now! Part of what you describe sounds like a feature request for Functions Frameworks (FF). I opened a new issue #141 and cc'ed you there. 

> So, what is the right way to debug a Pub/Sub Cloud Function?

For local testing, the Pub/Sub emulator and FF should suffice if you are okay with using `request`.
For remote testing, the official guide you linked is up to date. I see why you are confused because it does mean one needs to update their locally tested code when deploying the function. 
Alternatively, you may consider writing some unit and system tests, as described [here](https://cloud.google.com/functions/docs/testing/test-event?hl=en).
Once the function is deployed, the UI offers a lot actually. I always do a test in Cloud Console under "Testing" just to make sure.

<img width="400" alt="Screen Shot 2021-08-05 at 5 02 11 PM" src="https://user-images.githubusercontent.com/9518298/128420835-0b4ef630-115b-409b-aabb-d3a46b11555f.png">

**Comment by di** [comment]
Reopening this until we can update the example to use a background function instead of a HTTP function per #141.

**Comment by josh-gree** [comment]
Hi really great tool you have built here! 

I really want to just be able to use curl to simulate a Pub/Sub message - I dont want to have to run the whole emulator - is this possible?
