### ISSUE TITLE
How can I register sqlalchemy extension to the current flask application globally?

### ISSUE THREAD

**Issue by oxesoft** [GoogleCloudPlatform/functions-framework-python#24]
The default way of using sqlalchemy models is calling globally:
```
db = SQLAlchemy()
db.init_app(app)
```
I don't see a way to get the "app" globally with functions-framework. sqlalchemy doesn't allow us registering it after a request is made. The desired use case is a simple:
```
result = SomeTable.query.all()
```
More information about using Flask-SqlAlchemy is [here](https://flask-sqlalchemy.palletsprojects.com/en/2.x/contexts/).

**Comment by di** [comment]
Hi @oxesoft, thanks for the question.

Even though the Functions Framework uses Flask, and there is technically an `app` somewhere inside it, there is no way to get access it primarily because it won't be available to you in the Cloud Functions runtime either.

If you need access to an `app` variable, it sounds like you're building an application, not a function, and you might want to consider using Cloud Run instead (see the Python quickstart [here](https://cloud.google.com/run/docs/quickstarts/build-and-deploy)).
