### ISSUE TITLE
Reconsider adding gunicorn as required dependency

### ISSUE THREAD

**Issue by yuri-sergiichuk** [GoogleCloudPlatform/functions-framework-python#42]
In the PR #36, the Gunicorn server became the required dependency which means that each app will have to download the Gunicorn and moreover if you bundle the app as a package with `functions-framework`, the Gunicorn will be in that package as well.

While it looks like smth that ease development and deployment and allows bootstrapping production-ready instances faster, in many cases I've seen Docker configurations where the application itself is bundled as an installable module and the Gunicorn is set up only inside the actual runner container. Moreover, I'd say such a way allows developers to fine-tune their setup better. The other case is people just using different WSGI servers.

My suggestion is to roll-back the latest change and do not require gunicorn as a dependency.

**Comment by di** [comment]
Hi @yuri-sergiichuk, thanks for the issue.

We added gunicorn as a dependency because:
* we want to ensure that users have a production-ready HTTP server available to them,
* that they're not unintentionally using the Flask development server in production,
* and that they don't need to install and configure additional libraries.

That said, it's still possible to use different WSGI servers or even fine tune gunicorn as before. This isn't currently documented, so I created https://github.com/GoogleCloudPlatform/functions-framework-python/issues/43 to address it.

In addition, the gunicorn dependency is a requirement for Google's internal use of this library, so we're unlikely to revert this change unless it's somehow actively preventing users from using the Functions Framework.

Given that, I'm going to close this issue, but I appreciate you participating in the discussion here and on other issues!
