### ISSUE TITLE
Better document testing

### ISSUE THREAD

**Issue by ChristianSauer** [GoogleCloudPlatform/functions-framework-python#47]
Hi,
neither the docs or code examples mention how to set up tests - which I think is important for any non trivial function.

I currently hook up my tests like this:

```python
from flask import testing
import pytest
from functions_framework import create_app
import pathlib


@pytest.fixture
def client() -> testing.Client:
    target = "function_name"
    source = pathlib.Path(__file__).parent.parent / "main.py"

    with create_app(target, str(source)).test_client() as client:
        yield client

def test_something(client: testing.Client):
    rv = client.post('/', data="no json")
    assert rv.status_code == 400
```

this assumes that the test file is inside a test folder.

**Comment by di** [comment]
Hi @ChristianSauer, there's some existing documentation about this here: https://cloud.google.com/functions/docs/testing/test-overview, such as https://cloud.google.com/functions/docs/testing/test-http for testing HTTP functions.

Since this is really more "Cloud Functions" documentation than "Functions Framework" documentation, I think this project can just link to those pages if they sufficiently document how to test a function.

If not though, let me know and we can update that documentation as necessary.

**Comment by ChristianSauer** [comment]
I think it is also functions framework documentation - the framework abstracts away some details and that makes it difficult to get integration test up and running. 

The entry for integration testing is only for node currently: https://cloud.google.com/functions/docs/testing/test-http#integration_tests

I would suggest adding a paragraph detailing how to set up IT tests for this framework in this repo, e.g. showing how to get the testing.Client and how to work with it. 
That way, people don't have to know the internals of flask to work with the functions framework.

**Comment by di** [comment]
> The entry for integration testing is only for node currently: https://cloud.google.com/functions/docs/testing/test-http#integration_tests

Got it, we will definitely add some Python examples to those docs, thanks!

> I would suggest adding a paragraph detailing how to set up IT tests for this framework in this repo, e.g. showing how to get the testing.Client and how to work with it.
> That way, people don't have to know the internals of flask to work with the functions framework.

Good point, I will leave this open to address that.

**Comment by grant** [comment]
CC @ace-n: It looks like we have Node (on DevSite) and Java (not on DevSite), and no Python sample.

**Comment by grant** [comment]
Looks like we have a new integration test using the FF:

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/functions/helloworld/sample_http_test_integration.py

Does this help?

**Comment by martindufort** [comment]
This statement in the Readme file suggest that you can using the `gcloud` command line tool to deploy Cloud Functions locally on your development computer. This is not possible AFAIK. 

> After you've written your function, you can simply deploy it from your local machine using the gcloud command-line tool. Check out the Cloud Functions quickstart.

**Comment by ace-n** [comment]
@ChristianSauer thanks again for filing this issue. Seeing as we've added a sample in Python and there hasn't been much activity on this since then, I'm going to close the issue as fixed.

Please feel free to reopen if this is still an issue, or file a new issue if you have other concerns. Thanks! 🙂
